export const provincias2 = [
  {
    id: 1,
    name: "provincia_1",
    ciudad: [
      {
        id: 1,
        name: "provincia_1_ciudad_1",
      },
      {
        id: 2,
        name: "provincia_1_ciudad_2",
      },
      {
        id: 3,
        name: "provincia_1_ciudad_3",
      },
    ],
  },
  {
    id: 2,
    name: "provincia_2",
    ciudad: [
      {
        id: 1,
        name: "provincia_2_ciudad_1",
      },
      {
        id: 2,
        name: "provincia_2_ciudad_2",
      },
      {
        id: 3,
        name: "provincia_2_ciudad_3",
      },
      {
        id: 4,
        name: "provincia_2_ciudad_4",
      },
    ],
  },
  {
    id: 3,
    name: "provincia_3",
    ciudad: [
      {
        id: 1,
        name: "provincia_3_ciudad_1",
      },
      {
        id: 2,
        name: "provincia_3_ciudad_2",
      },
    ],
  },
];

export let provincias = [
  {
    id: 1,
    name: "Buenos Aires",
    ciudad: [
      { id: 1, name: "Almirante Brown" },
      { id: 2, name: "Avellaneda" },
      { id: 3, name: "Berazategui" },
      { id: 4, name: "Berisso" },
      { id: 5, name: "Brandsen" },
      { id: 6, name: "Campana" },
      { id: 7, name: "Cañuelas" },
      { id: 8, name: "Ensenada" },
      { id: 9, name: "Escobar" },
      { id: 10, name: "Esteban Echeverría" },
      { id: 11, name: "Exaltación de la Cruz" },
      { id: 12, name: "Ezeiza" },
      { id: 13, name: "Florencio Varela" },
      { id: 14, name: "General Las Heras" },
      { id: 15, name: "General Rodríguez" },
      { id: 16, name: "General San Martín" },
      { id: 17, name: "Hurlingham" },
      { id: 18, name: "Ituzaingó" },
      { id: 19, name: "José C. Paz" },
      { id: 20, name: "La Matanza" },
      { id: 21, name: "La Plata" },
      { id: 22, name: "Lanús" },
      { id: 23, name: "Lomas de Zamora" },
      { id: 24, name: "Luján" },
      { id: 25, name: "Malvinas Argentinas" },
      { id: 26, name: "Marcos Paz" },
      { id: 27, name: "Merlo" },
      { id: 28, name: "Moreno" },
      { id: 29, name: "Morón" },
      { id: 30, name: "Pilar" },
      { id: 31, name: "Presidente Perón" },
      { id: 32, name: "Quilmes" },
      { id: 33, name: "San Fernando" },
      { id: 34, name: "San Isidro" },
      { id: 35, name: "San Miguel" },
      { id: 36, name: "San Vicente" },
      { id: 37, name: "Tigre" },
      { id: 38, name: "Tres de Febrero" },
      { id: 39, name: "Vicente López" },
      { id: 40, name: "Zárate" },
    ],
  },
]







export const provincias3 = [
  {
    id: 1,
    name: "Buenos Aires",
    ciudad: [
      { id: 1, name: "Almirante Brown" },
      { id: 2, name: "Avellaneda" },
      { id: 3, name: "Berazategui" },
      { id: 4, name: "Berisso" },
      { id: 5, name: "Brandsen" },
      { id: 6, name: "Campana" },
      { id: 7, name: "Cañuelas" },
      { id: 8, name: "Ensenada" },
      { id: 9, name: "Escobar" },
      { id: 10, name: "Esteban Echeverría" },
      { id: 11, name: "Exaltación de la Cruz" },
      { id: 12, name: "Ezeiza" },
      { id: 13, name: "Florencio Varela" },
      { id: 14, name: "General Las Heras" },
      { id: 15, name: "General Rodríguez" },
      { id: 16, name: "General San Martín" },
      { id: 17, name: "Hurlingham" },
      { id: 18, name: "Ituzaingó" },
      { id: 19, name: "José C. Paz" },
      { id: 20, name: "La Matanza" },
      { id: 21, name: "La Plata" },
      { id: 22, name: "Lanús" },
      { id: 23, name: "Lomas de Zamora" },
      { id: 24, name: "Luján" },
      { id: 25, name: "Malvinas Argentinas" },
      { id: 26, name: "Marcos Paz" },
      { id: 27, name: "Merlo" },
      { id: 28, name: "Moreno" },
      { id: 29, name: "Morón" },
      { id: 30, name: "Pilar" },
      { id: 31, name: "Presidente Perón" },
      { id: 32, name: "Quilmes" },
      { id: 33, name: "San Fernando" },
      { id: 34, name: "San Isidro" },
      { id: 35, name: "San Miguel" },
      { id: 36, name: "San Vicente" },
      { id: 37, name: "Tigre" },
      { id: 38, name: "Tres de Febrero" },
      { id: 39, name: "Vicente López" },
      { id: 40, name: "Zárate" },
    ],
  },
  {
    id: 2,
    name: "Catamarca",
    ciudad: [
      { id: 1, name: "Ambato" },
      { id: 2, name: "Ancasti" },
      { id: 3, name: "Andalgalá" },
      { id: 4, name: "Antofagasta de la Sierra" },
      { id: 5, name: "Belén" },
      { id: 6, name: "Capayán" },
      { id: 7, name: "Capital" },
      { id: 8, name: "El Alto" },
      { id: 9, name: "Fray Mamerto Esquiú" },
      { id: 10, name: "La Paz" },
      { id: 11, name: "Paclín" },
      { id: 12, name: "Pomán" },
      { id: 13, name: "Santa María" },
      { id: 14, name: "Santa Rosa" },
      { id: 15, name: "Tinogasta" },
      { id: 16, name: "Valle Viejo" },
    ],
  },
  {
    id: 3,
    name: "Chaco",
    ciudad: [
      { id: 1, name: "Almirante Brown" },
      { id: 2, name: "Bermejo" },
      { id: 3, name: "Chacabuco" },
      { id: 4, name: "Comandante Fernández" },
      { id: 5, name: "Doce de Octubre" },
      { id: 6, name: "Dos de Abril" },
      { id: 7, name: "Fray Justo Santa María de Oro" },
      { id: 8, name: "General Belgrano" },
      { id: 9, name: "General Donovan" },
      { id: 10, name: "General Güemes" },
      { id: 11, name: "Independencia" },
      { id: 12, name: "Libertad" },
      { id: 13, name: "Libertador General San Martín" },
      { id: 14, name: "Maipú" },
      { id: 15, name: "Mayor Luis Jorge Fontana" },
      { id: 16, name: "Nueve de Julio" },
      { id: 17, name: "O'Higgins" },
      { id: 18, name: "Presidencia de la Plaza" },
      { id: 19, name: "Primero de Mayo" },
      { id: 20, name: "Quitilipi" },
      { id: 21, name: "San Fernando" },
      { id: 22, name: "San Lorenzo" },
      { id: 23, name: "Sargento Cabral" },
      { id: 24, name: "Tapenagá" },
      { id: 25, name: "Veinticinco de Mayo" },
    ],
  },
  {
    id: 4,
    name: "Chubut",
    ciudad: [
      { id: 1, name: "Atlántico" },
      { id: 2, name: "Biedma" },
      { id: 3, name: "Cushamen" },
      { id: 4, name: "Escalante" },
      { id: 5, name: "Florentino Ameghino" },
      { id: 6, name: "Futaleufú" },
      { id: 7, name: "Gaiman" },
      { id: 8, name: "Gastre" },
      { id: 9, name: "Languiñeo" },
      { id: 10, name: "Mártires" },
      { id: 11, name: "Paso de Indios" },
      { id: 12, name: "Rawson" },
      { id: 13, name: "Río Senguer" },
      { id: 14, name: "Sarmiento" },
      { id: 15, name: "Tehuelches" },
      { id: 16, name: "Telsen" },
    ],
  },
  {
    id: 5,
    name: "Córdoba",
    ciudad: [
      { id: 1, name: "Alta Gracia" },
      { id: 2, name: "Bell Ville" },
      { id: 3, name: "Córdoba" },
      { id: 4, name: "Cosquín" },
      { id: 5, name: "Cruz del Eje" },
      { id: 6, name: "Deán Funes" },
      { id: 7, name: "Jesús María" },
      { id: 8, name: "La Carlota" },
      { id: 9, name: "Laboulaye" },
      { id: 10, name: "Marcos Juárez" },
      { id: 11, name: "Oliva" },
      { id: 12, name: "Río Cuarto" },
      { id: 13, name: "Salsacate" },
      { id: 14, name: "San Agustín" },
      { id: 15, name: "San Carlos Minas" },
      { id: 16, name: "San Francisco" },
      { id: 17, name: "San Francisco del Chañar" },
      { id: 18, name: "Santa Rosa de Río Primero" },
      { id: 19, name: "Villa Cura Brochero" },
      { id: 20, name: "Villa de María" },
      { id: 21, name: "Villa del Rosario" },
      { id: 22, name: "Villa del Totoral" },
      { id: 23, name: "Villa Dolores" },
      { id: 24, name: "Villa Huidobro" },
      { id: 25, name: "Villa María" },
      { id: 26, name: "Villa Tulumba" },
    ],
  },
  {
    id: 6,
    name: "Corrientes",
    ciudad: [
      { id: 1, name: "Bella Vista" },
      { id: 2, name: "San Antonio de Itatí" },
      { id: 3, name: "Corrientes" },
      { id: 4, name: "Concepción" },
      { id: 5, name: "Curuzú Cuatiá" },
      { id: 6, name: "Empedrado" },
      { id: 7, name: "Esquina" },
      { id: 8, name: "Alvear" },
      { id: 9, name: "Caá Catí" },
      { id: 10, name: "Goya" },
      { id: 11, name: "Itatí" },
      { id: 12, name: "Ituzaingó" },
      { id: 13, name: "Santa Lucía" },
      { id: 14, name: "Mburucuyá" },
      { id: 15, name: "Mercedes" },
      { id: 16, name: "Monte Caseros" },
      { id: 17, name: "Paso de los Libres" },
      { id: 18, name: "Saladas" },
      { id: 19, name: "San Cosme" },
      { id: 20, name: "San Luis del Palmar" },
      { id: 21, name: "La ruz" },
      { id: 22, name: "San Miguel" },
      { id: 23, name: "San Roque" },
      { id: 24, name: "Santo Tomé" },
      { id: 25, name: "Sauce" },
      { id: 26, name: "Villa Tulumba" },
    ],
  },
  {
    id: 7,
    name: "Entre Ríos",
    ciudad: [
      { id: 1, name: "Colón" },
      { id: 2, name: "Concordia" },
      { id: 3, name: "Diamante" },
      { id: 4, name: "Federación" },
      { id: 5, name: "Federal" },
      { id: 6, name: "San José de Feliciano" },
      { id: 7, name: "Gualeguay" },
      { id: 8, name: "Gualeguaychú" },
      { id: 9, name: "Villa Paranacito" },
      { id: 10, name: "La Paz" },
      { id: 11, name: "Nogoyá" },
      { id: 12, name: "Paraná" },
      { id: 13, name: "San alvador" },
      { id: 14, name: "Rosario del Tala" },
      { id: 15, name: "Concepción del Uruguay" },
      { id: 16, name: "Victoria" },
      { id: 17, name: "Villaguay" },
      { id: 18, name: "Saladas" },
      { id: 19, name: "San Cosme" },
      { id: 20, name: "San Luis del Palmar" },
      { id: 21, name: "La Cruz" },
      { id: 22, name: "San Miguel" },
      { id: 23, name: "San Roque" },
      { id: 24, name: "Santo Tomé" },
      { id: 25, name: "Sauce" },
      { id: 26, name: "Villa Tulumba" },
      { id: 27, name: "" },
    ],
  },
  {
    id: 8,
    name: "Formosa",
    ciudad: [
      { id: 1, name: "Laguna Yema" },
      { id: 2, name: "Formosa" },
      { id: 3, name: "San Francisco de Laishí" },
      { id: 4, name: "Ingeniero Juárez" },
      { id: 5, name: "Comandante Fontana" },
      { id: 6, name: "El Espinillo" },
      { id: 7, name: "Clorinda" },
      { id: 8, name: "Pirané" },
      { id: 9, name: "General Mosconi3​" },
    ],
  },
  {
    id: 9,
    name: "Jujuy",
    ciudad: [
      { id: 1, name: "Cochinoca" },
      { id: 2, name: "Dr. Manuel Belgrano" },
      { id: 3, name: "El Carmen" },
      { id: 4, name: "Humahuaca" },
      { id: 5, name: "Ledesma" },
      { id: 6, name: "Palpalá" },
      { id: 7, name: "Rinconada" },
      { id: 8, name: "San Antonio" },
      { id: 9, name: "San Pedro" },
      { id: 10, name: "Santa Bárbara" },
      { id: 11, name: "Santa Catalina" },
      { id: 12, name: "Susques" },
      { id: 13, name: "Tilcara" },
      { id: 14, name: "Tumbaya" },
      { id: 15, name: "Valle Grande" },
      { id: 16, name: "Yavi" },
    ],
  },
  {
    id: 10,
    name: "La Pampa",
    ciudad: [
      { id: 1, name: "Atreucó" },
      { id: 2, name: "Caleu Caleu" },
      { id: 3, name: "Capital" },
      { id: 4, name: "Catriló" },
      { id: 5, name: "Chalileo" },
      { id: 6, name: "Chapaleufú" },
      { id: 7, name: "Chical Co" },
      { id: 8, name: "Conhelo" },
      { id: 9, name: "Curacó" },
      { id: 10, name: "Guatraché" },
      { id: 11, name: "Hucal" },
      { id: 12, name: "Lihuel Calel" },
      { id: 13, name: "Limay Mahuida" },
      { id: 14, name: "Loventué" },
      { id: 15, name: "Maracó" },
      { id: 16, name: "Puelén" },
      { id: 17, name: "Quemú Quemú" },
      { id: 18, name: "Rancul" },
      { id: 19, name: "Realicó" },
      { id: 20, name: "Toay" },
      { id: 21, name: "Trenel" },
      { id: 22, name: "Utracán" },
    ],
  },
  {
    id: 11,
    name: "La Rioja",
    ciudad: [
      { id: 1, name: "Arauco" },
      { id: 2, name: "Capital" },
      { id: 3, name: "Castro Barros" },
      { id: 4, name: "Chamical" },
      { id: 5, name: "Chilecito" },
      { id: 6, name: "Coronel Felipe Varela" },
      { id: 7, name: "Famatina" },
      { id: 8, name: "General Ángel V. Peñaloza" },
      { id: 9, name: "General Belgrano" },
      { id: 10, name: "General Juan Facundo Quiroga" },
      { id: 11, name: "General Lamadrid" },
      { id: 12, name: "General Ocampo" },
      { id: 13, name: "General San Martín" },
      { id: 14, name: "Independencia" },
      { id: 15, name: "Rosario Vera Peñaloza" },
      { id: 16, name: "San Blas de los Sauces" },
      { id: 17, name: "Sanagasta" },
      { id: 18, name: "Vinchina" },
    ],
  },
  {
    id: 12,
    name: "Mendoza",
    ciudad: [
      { id: 1, name: "Capital" },
      { id: 2, name: "General Alvear" },
      { id: 3, name: "Godoy Cruz" },
      { id: 4, name: "Guaymallén" },
      { id: 5, name: "Junín" },
      { id: 6, name: "La Paz" },
      { id: 7, name: "Las Heras" },
      { id: 8, name: "Lavalle" },
      { id: 9, name: "Luján de Cuyo" },
      { id: 10, name: "Maipú" },
      { id: 11, name: "Malargüe" },
      { id: 12, name: "Rivadavia" },
      { id: 13, name: "San Carlos" },
      { id: 14, name: "General San Martín" },
      { id: 15, name: "San Rafael" },
      { id: 16, name: "Santa Rosa" },
      { id: 17, name: "Tunuyán" },
      { id: 18, name: "Tupungato" },
    ],
  },
  {
    id: 13,
    name: "Misiones",
    ciudad: [
      { id: 1, name: "Capital" },
      { id: 2, name: "Oberá" },
      { id: 3, name: "Iguazú" },
      { id: 4, name: "Eldorado" },
      { id: 5, name: "Guaraní" },
      { id: 6, name: "San Ignacio" },
      { id: 7, name: "Cainguás" },
      { id: 8, name: "Libertador Gral. San Martín" },
      { id: 9, name: "Leandro N. Alem" },
      { id: 10, name: "General Manuel Belgrano" },
      { id: 11, name: "Apóstoles" },
      { id: 12, name: "Montecarlo" },
      { id: 13, name: "San Pedro" },
      { id: 14, name: "25 de mayo" },
      { id: 15, name: "Candelaria" },
      { id: 16, name: "San Javier" },
      { id: 17, name: "Concepción" },
    ],
  },
  {
    id: 14,
    name: "Neuquén",
    ciudad: [
      { id: 1, name: "Aluminé" },
      { id: 2, name: "Añelo" },
      { id: 3, name: "Catán Lil" },
      { id: 4, name: "Chos Malal" },
      { id: 5, name: "Collón Curá" },
      { id: 6, name: "Confluencia" },
      { id: 7, name: "Huiliches" },
      { id: 8, name: "Lácar" },
      { id: 9, name: "Loncopué" },
      { id: 10, name: "Los Lagos" },
      { id: 11, name: "Minas" },
      { id: 12, name: "Ñorquín" },
      { id: 13, name: "Pehuenches" },
      { id: 14, name: "Picún Leufú" },
      { id: 15, name: "Picunches" },
      { id: 16, name: "Zapala" },
    ],
  },
  {
    id: 15,
    name: "Rio Negro",
    ciudad: [
      { id: 1, name: "Viedma" },
      { id: 2, name: "Choele Choel" },
      { id: 3, name: "San Carlos de Bariloche" },
      { id: 4, name: "General Conesa" },
      { id: 5, name: "El Cuy" },
      { id: 6, name: "General Roca" },
      { id: 7, name: "Sierra Colorada" },
      { id: 8, name: "Ñorquinco" },
      { id: 9, name: "Río Colorado" },
      { id: 10, name: "Pilcaniyeu" },
      { id: 11, name: "San Antonio Oeste" },
      { id: 12, name: "Valcheta" },
      { id: 13, name: "Maquinchao" },
    ],
  },
  {
    id: 16,
    name: "Salta",
    ciudad: [
      { id: 1, name: "de la Capital" },
      { id: 2, name: "de Orán" },
      { id: 3, name: "General José de San Martín" },
      { id: 4, name: "de Anta" },
      { id: 5, name: "General Güemes" },
      { id: 6, name: "de Metán" },
      { id: 7, name: "Rosario de Lerma" },
      { id: 8, name: "de Cerrillos" },
      { id: 9, name: "de Rivadavia" },
      { id: 10, name: "de Rosario de la Frontera" },
      { id: 11, name: "de Chicoana" },
      { id: 12, name: "de Cafayate" },
      { id: 13, name: "Santa Victoria" },
      { id: 14, name: "de La Caldera" },
      { id: 15, name: "La Viña" },
      { id: 16, name: "de Cachi" },
      { id: 17, name: "de San Carlos" },
      { id: 18, name: "de Los Andes" },
      { id: 19, name: "de Iruya" },
      { id: 20, name: "de La Candelaria" },
      { id: 21, name: "de Molinos" },
      { id: 22, name: "de Guachipas" },
      { id: 23, name: "La Poma" },
    ],
  },
  {
    id: 17,
    name: "San Juan",
    ciudad: [
      { id: 1, name: "Capital" },
      { id: 2, name: "Rawson" },
      { id: 3, name: "Chimbas" },
      { id: 4, name: "Rivadavia" },
      { id: 5, name: "Santa Lucía" },
      { id: 6, name: "Pocito" },
      { id: 7, name: "Caucete" },
      { id: 8, name: "Jáchal" },
      { id: 9, name: "Albardón" },
      { id: 10, name: "Sarmiento" },
      { id: 11, name: "25 de mayo" },
      { id: 12, name: "San Martín" },
      { id: 13, name: "Calingasta" },
      { id: 14, name: "9 de julio" },
      { id: 15, name: "Angaco" },
      { id: 16, name: "Valle Fértil" },
      { id: 17, name: "Iglesia" },
      { id: 18, name: "Ullum" },
      { id: 19, name: "Zonda" },
    ],
  },
  {
    id: 18,
    name: "San Luis",
    ciudad: [
      { id: 1, name: "San Francisco del Monte de Oro" },
      { id: 2, name: "Villa General Roca" },
      { id: 3, name: "Concarán" },
      { id: 4, name: "La Toma" },
      { id: 5, name: "Villa Mercedes" },
      { id: 6, name: "Buena Esperanza" },
      { id: 7, name: "San Luis" },
      { id: 8, name: "Santa Rosa del Conlara" },
      { id: 9, name: "Libertador General San Martín" },
    ],
  },
  {
    id: 19,
    name: "Santa Cruz",
    ciudad: [
      { id: 1, name: "Corpen Aike" },
      { id: 2, name: "Deseado" },
      { id: 3, name: "Güer Aike" },
      { id: 4, name: "Lago Argentino" },
      { id: 5, name: "Lago Buenos Aires" },
      { id: 6, name: "Magallanes" },
      { id: 7, name: "Río Chico" },
    ],
  },
  {
    id: 20,
    name: "Santa Fe",
    ciudad: [
      { id: 1, name: "Belgrano" },
      { id: 2, name: "Caseros" },
      { id: 3, name: "Castellanos" },
      { id: 4, name: "Constitución" },
      { id: 5, name: "Garay" },
      { id: 6, name: "General López" },
      { id: 7, name: "General Obligado" },
      { id: 8, name: "Iriondo" },
      { id: 9, name: "La Capital" },
      { id: 10, name: "Las Colonias" },
      { id: 11, name: "Nueve de Julio" },
      { id: 12, name: "Rosario" },
      { id: 13, name: "San Cristóbal" },
      { id: 14, name: "San Javier" },
      { id: 15, name: "San Jerónimo" },
      { id: 16, name: "San Justo" },
      { id: 17, name: "San Lorenzo" },
      { id: 18, name: "San Martín" },
      { id: 19, name: "Vera" },
    ],
  },
  {
    id: 21,
    name: "Santiago del Estero",
    ciudad: [
      { id: 1, name: "Aguirre" },
      { id: 2, name: "Alberdi" },
      { id: 3, name: "Atamisqui" },
      { id: 4, name: "Avellaneda" },
      { id: 5, name: "Banda" },
      { id: 6, name: "Belgrano" },
      { id: 7, name: "Choya" },
      { id: 8, name: "Copo" },
      { id: 9, name: "Figueroa" },
      { id: 10, name: "General Taboada" },
      { id: 11, name: "Guasayán" },
      { id: 12, name: "Jiménez" },
      { id: 13, name: "Juan Felipe Ibarra" },
      { id: 14, name: "Juan Francisco Borges" },
      { id: 15, name: "Loreto" },
      { id: 16, name: "Mitre" },
      { id: 17, name: "Moreno" },
      { id: 18, name: "Ojo de Agua" },
      { id: 19, name: "Pellegrini" },
      { id: 20, name: "Quebrachos" },
      { id: 21, name: "Río Hondo" },
      { id: 22, name: "Rivadavia" },
      { id: 23, name: "Robles" },
      { id: 24, name: "Salavina" },
      { id: 25, name: "San Martín" },
      { id: 26, name: "Sarmiento" },
      { id: 27, name: "Silípica" },
    ],
  },
  {
    id: 22,
    name: "Tierra del Fuego, Antártida e Islas del Atlántico Sur",
    ciudad: [
      { id: 1, name: "Antártida Argentina" },
      { id: 2, name: "Islas del Atlántico Sur" },
      { id: 3, name: "Río Grande" },
      { id: 4, name: "Tolhuin" },
      { id: 5, name: "Ushuaia" },
    ],
  },
  {
    id: 23,
    name: "Tucuman",
    cuidad: [
      { id: 1, name: "Burruyacú" },
      { id: 2, name: "Capital" },
      { id: 3, name: "Chicligasta" },
      { id: 4, name: "Cruz Alta" },
      { id: 5, name: "Famaillá" },
      { id: 6, name: "Graneros" },
      { id: 7, name: "Juan Bautista Alberdi" },
      { id: 8, name: "La Cocha" },
      { id: 9, name: "Leales" },
      { id: 10, name: "Lules" },
      { id: 11, name: "Monteros" },
      { id: 12, name: "Río Chico" },
      { id: 13, name: "Simoca" },
      { id: 14, name: "Tafí del Valle" },
      { id: 15, name: "Tafí Viejo" },
      { id: 16, name: "Trancas" },
      { id: 17, name: "Yerba Buena" },
    ],
  },
];

