import {
  people01,
  people02,
  people03,
  people04,
  people05,
  people06,
  people07,
  people08,
} from "../assets";

export const reviews = [
  {
    id: 1,
    firstName: "Lara",
    lastName: "Moyano",
    image: "https://avatars.githubusercontent.com/u/99929493?v=4",
    review: "Lara Moyano",
    github: "https://github.com/VicLara22",
  },
  {
    id: 2,
    firstName: "Victor",
    lastName: "Colquichagua",
    image: "https://avatars.githubusercontent.com/u/69781012?v=4",
    review: "Victor Colquichagua",
    github: "https://github.com/victor-cp",
  },
  {
    id: 3,
    firstName: "Fray",
    lastName: "Toledo",
    image: "https://avatars.githubusercontent.com/u/82120504?v=4",
    review: "Fray Toledo",
    github: "https://github.com/fraynilson2003",
  },
  {
    id: 4,
    firstName: "Jose",
    lastName: "Flores",
    image: "https://avatars.githubusercontent.com/u/105085111?v=4",
    review: "Jose Flores",
    github: "https://github.com/josephflo",
  },
  {
    id: 5,
    firstName: "Mikhail",
    lastName: "Baez",
    image: "https://avatars.githubusercontent.com/u/113799591?v=4",
    review: "Mikhail Baez",
    github: "https://github.com/mikbaor",
  },
  // {
  //   id: 6,
  //   firstName: "User6",
  //   lastName: "Lastname1",
  //   image: people06,
  //   review: "Segura y eficaz",
  // },
  // {
  //   id: 7,
  //   firstName: "User7",
  //   lastName: "Lastname1",
  //   image: people07,
  //   review: "Muy útil la recomiendo",
  // },
  // {
  //   id: 8,
  //   firstName: "User8",
  //   lastName: "Lastname1",
  //   image: people08,
  //   review: "Adecuada a lo que buscas",
  // },
];
