export const ActionTypes = {
  GET_NAME: "GET_NAME",
  CREATE_USER: "CREATE_USER",
  USER_LOGIN: "USER_LOGIN",
  ADD_JOB: "ADD_JOB",
  GET_JOBS: "GET_JOBS",
  GET_JOB_BY_ID: "GET_JOB_BY_ID",
  GET_USERS: "GET_USERS",
  GET_SERVICE: "GET_SERVICE",
};
