export const ActionTypes = {
  GET_NAME: "GET_NAME",
  CREATE_USER: "CREATE_USER",
  USER_LOGIN: "USER_LOGIN",
  ADD_JOB: "ADD_JOB",
  GET_JOBS: "GET_JOBS",
  GET_JOB_BY_ID: "GET_JOB_BY_ID",
  GET_USERS: "GET_USERS",
  GET_USER_AUTH0_ID: "GET_USER_AUTH0_ID",
  GET_SERVICE: "GET_SERVICE",
  GET_SERVICES: "GET_SERVICES",
  FILTER_BY_JOBS: "FILTER_BY_JOBS",
  ORDER_BY_NAME: "ORDER_BY_NAME",
  CREATE_SERVICE: "CREATE_SERVICE",
  FILTER_MODEL: "FILTER_MODEL",
  ORDER_BY_NAME:' ORDER_BY_NAME',
  ORDER_BY_ROLE:' ORDER_BY_ROLE',
  ORDER_BY_STATE:'ORDER_BY_STATE',
  ORDER_BY_NAME_JOB:'ORDER_BY_NAME_JOB',
  ORDER_BY_STATE_JOB:'ORDER_BY_STATE_JOB',
  USER_DETAIL: "USER_DETAIL",
  CLEAN_USER_DETAIL: "CLEAN_USER_DETAIL",
  PROFESSIONAL_DETAIL: "PROFESSIONAL_DETAIL",

  GET_ALL_USERS_FILTRADO: "GET_ALL_USERS_FILTRADO",

  CONFIG_FILTER_SERVICES: "CONFIG_FILTER_SERVICES",
  CONFIG_FILTER_USER: "CONFIG_FILTER_USER",

  //REGISTER AND LOGIN
  REGISTER_USER_AND_LOGIN: "REGISTER_USER_AND_LOGIN"
};

