export let ActionTypes = {
  GET_NAME: "GET_NAME",
  CREATE_USER: "CREATE_USER",
  USER_LOGIN: "USER_LOGIN",
  ADD_JOB: "ADD_JOB",
  GET_JOBS: "GET_JOBS",
  GET_JOB_BY_ID: "GET_JOB_BY_ID",
  GET_USERS: "GET_USERS",
  GET_USER_AUTH0_ID: "GET_USER_AUTH0_ID",
  GET_SERVICE: "GET_SERVICE",
  GET_SERVICES: "GET_SERVICES",
  GET_SERVICES_DASBOARD: "GET_SERVICES_DASBOARD",
  UPDATE_USER : "UPDATE_USER",

  FILTER_BY_JOBS: "FILTER_BY_JOBS",
  ORDER_BY_NAME: "ORDER_BY_NAME",
  CREATE_SERVICE: "CREATE_SERVICE",
  FILTER_MODEL: "FILTER_MODEL",
  ORDER_BY_ROLE: " ORDER_BY_ROLE",
  ORDER_BY_STATE: "ORDER_BY_STATE",
  ORDER_BY_NAME_JOB: "ORDER_BY_NAME_JOB",
  ORDER_BY_STATE_JOB: "ORDER_BY_STATE_JOB",
  USER_DETAIL: "USER_DETAIL",
  CLEAN_USER_DETAIL: "CLEAN_USER_DETAIL",
  PROFESSIONAL_DETAIL: "PROFESSIONAL_DETAIL",
  MY_TRABAJOS: "MY_TRABAJOS",
  MY_SERVICES: "MY_SERVICES",
  MY_POSTULACIONES: "MY_POSTULACIONES",

  SERVICE_DETAIL: "SERVICE_DETAIL",
  CLEAN_SERVICE_DETAIL: "CLEAN_SERVICE_DETAIL",

  GET_ALL_USERS_FILTRADO: "GET_ALL_USERS_FILTRADO",

  // DETAIL SERVICE
  SUGGESTION_SERVICES: "SUGGESTION_SERVICES",
  STATE_SUGGESTION_SERVICE: "STATE_SUGGESTION_SERVICE",
  CLEAN_SUGGESTION_SERVICE: "CLEAN_SUGGESTION_SERVICE",
  APPLY_TO_SERVICE: "APPLY_TO_SERVICE",

  CONFIG_FILTER_SERVICES: "CONFIG_FILTER_SERVICES",
  CONFIG_FILTER_PERFIL_OFFER: "CONFIG_FILTER_PERFIL_OFFER",

  CONFIG_FILTER_PERFIL_JOBS: "CONFIG_FILTER_PERFIL_JOBS",

  CONFIG_FILTER_USER: "CONFIG_FILTER_USER",
  CONFIG_FILTER_ALL_USERS: "CONFIG_FILTER_ALL_USERS",
  CONFIG_FILTER_PERFIL_POSTULACIONES: "CONFIG_FILTER_PERFIL_POSTULACIONES",

  CLEAN_JOB_BY_ID: "CLEAN_JOB_BY_ID",
  CLEAN_ALL_SERVICES: "CLEAN_ALL_SERVICES",

  //REGISTER AND LOGIN
  REGISTER_USER_AND_LOGIN: "REGISTER_USER_AND_LOGIN",
  GET_DASHBOARD_CONTENT: "GET_DASHBOARD_CONTENT",

  //
  ACCEPT_USER: "ACCEPT_USER",
  STATE_SELECTED: "STATE_SELECTED",
  STATE_SELECTED_COMUN: "STATE_SELECTED_COMUN",

  // CLEAN
  CLEAN_OFFER_PERFIL_PROFESSIONAL: "CLEAN_OFFER_PERFIL_PROFESSIONAL",
  CLEAN_TRABAJOS_PERFIL_PROFESSIONAL: "CLEAN_TRABAJOS_PERFIL_PROFESSIONAL",
  CLEAN_POSTULACIONES_PERFIL_PROFESSIONAL:
    "CLEAN_POSTULACIONES_PERFIL_PROFESSIONAL",

  UPDATE_USER_ADMIN: "UPDATE_USER_ADMIN",
  INACTIVE_SERVICE: "INACTIVE_SERVICE",
  ACTIVATE_SERVICE:"ACTIVATE_SERVICE"
};
